// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// eigen_test
int eigen_test();
RcppExport SEXP _scbursts_eigen_test() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(eigen_test());
    return rcpp_result_gen;
END_RCPP
}
// hjcfit_test
std::string hjcfit_test();
RcppExport SEXP _scbursts_hjcfit_test() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(hjcfit_test());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scbursts_eigen_test", (DL_FUNC) &_scbursts_eigen_test, 0},
    {"_scbursts_hjcfit_test", (DL_FUNC) &_scbursts_hjcfit_test, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_scbursts(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
