# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A maximum likelihood estimate for a Q-Matrix with a fixed number
#' of states. Computes the likelihood of a kinetic model given
#' observed bursts, with missed event correction, using the HJCFIT
#' library. This function is an interface for Log10Likelihood from
#' HJCFIT.
#' 
#' https://github.com/DCPROGS/HJCFIT
#' 
#' See the link above and the references therein for details.
#'
#' @param qmatrix Initial guess qmatrix.
#' @param nopen Number of open states in the matrix.
#' @param bursts A list of bursts.
#' @param tau Maximum length of the missed events.
#' @param nmax The exact missed-event likelihood will be computed for 't < n_max * tau'
#' @param xtol Tolerance criteria for brentq().
#' @param rtol Tolerance criteria for brentq().
#' @param itermax Maximum number of iteration when calling brentq().
#' @param REQMIN Nelder-Mead parameter: stop if within required distance.
#' @param KONVGE Nelder-Mead parameter: check convergence every KONVGE steps.
#' @param KMAX Nelder-Mead parameter: maximum number of iterations.
#' @return A qmatrix kinetic model which numerically maximizes likelihood.
#' @export
cpp_hjcfit_likelihood_maximize <- function(qmatrix, nopen, bursts, tau, nmax = 2L, xtol = 0.0000000001, rtol = 0.0000000001, itermax = 100L, REQMIN = 0.000001, KONVGE = 10L, KMAX = 1000L) {
    .Call('_scbursts_cpp_hjcfit_likelihood_maximize', PACKAGE = 'scbursts', qmatrix, nopen, bursts, tau, nmax, xtol, rtol, itermax, REQMIN, KONVGE, KMAX)
}

#' Computes the likelihood of a kinetic model given observed bursts,
#' with missed event correction, using the HJCFIT library. This
#' function is an interface for Log10Likelihood from HJCFIT.
#' 
#' https://github.com/DCPROGS/HJCFIT
#' 
#' See the link above and the references therein for details.
#'
#' NOTE: It is slow to call this over and over again.
#'
#' @param qmatrix Initial guess qmatrix.
#' @param nopen Number of open states in the matrix
#' @param bursts A list of bursts
#' @param tau Maximum length of the missed events
#' @param nmax The exact missed-event likelihood will be computed for 't < n_max * tau'
#' @param xtol Tolerance criteria for brentq().
#' @param rtol Tolerance criteria for brentq().
#' @param itermax Maximum number of iteration when calling brentq().
#' @return The log10-likelihood of the model given the burst sequence.
#' @export
cpp_hjcfit_likelihood <- function(qmatrix, nopen, bursts, tau, nmax = 2L, xtol = 0.0000000001, rtol = 0.0000000001, itermax = 100L) {
    .Call('_scbursts_cpp_hjcfit_likelihood', PACKAGE = 'scbursts', qmatrix, nopen, bursts, tau, nmax, xtol, rtol, itermax)
}

