# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Testing documentation with Rcpp
#'
#' @return           A number
#' @export
eigen_test <- function() {
    .Call('_scbursts_eigen_test', PACKAGE = 'scbursts')
}

#' Testing documentation with Rcpp
#'
#' @return           A string
#' @export
hjcfit_test <- function() {
    .Call('_scbursts_hjcfit_test', PACKAGE = 'scbursts')
}

